# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpA6eiopu8tG4SVD9L-SXVTF1VuRP0lB
"""

import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Load your CSV file (replace 'breast_cancer.csv' with your filename)
df = pd.read_csv('breast-cancer.csv')

# Drop 'id' column because it's not a feature
df = df.drop('id', axis=1)

# Encode target variable 'diagnosis' from 'M'/'B' to 1/0
le = LabelEncoder()
df['diagnosis'] = le.fit_transform(df['diagnosis'])  # M=1, B=0

# Split features and target
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

# Split dataset into train and test (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Initialize Random Forest model
model = RandomForestClassifier(random_state=42)

# Setup 5-fold cross-validation on training data
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation on training set
cv_scores = cross_val_score(model, X_train, y_train, cv=kf)
print("Cross-validation accuracies:", cv_scores)
print("Mean CV accuracy:", cv_scores.mean())

# Train final model on entire training data
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Evaluate test accuracy
test_accuracy = accuracy_score(y_test, y_pred)
print(f"Test set accuracy: {test_accuracy:.4f}")